package main

import (
	"fmt"
	"runtime"
)

func main() {
	fmt.Printf("Platform-Specific Vulnerability Test Application\n")
	fmt.Printf("Running on: %s/%s\n\n", runtime.GOOS, runtime.GOARCH)

	// Execute common code with vulnerability
	// This vulnerability is FIXED on macOS but REMAINS on Windows
	ProcessUserInput()

	// Load and execute platform-specific code
	// These files are generated by the build tool
	fmt.Printf("Executing %s-specific code...\n", runtime.GOOS)
	PlatformSpecificFunction()

	fmt.Println("\nApplication completed successfully")
}
